version: '3.7'
services:
    jenkinsMyNode:
        image: 'jenkins/jenkins:lts-jdk11'
        ports:
        - '8080:8080'
        - '50000:50000'
        volumes:
          - jenkins_home:/var/jenkins_home
          - c:/myapp:/var/jenkins_home/workspace/myapp
          
    unixNode:
        image: 'amd64/ubuntu'       
volumes:
  jenkins_home: